import { McpServer } from "@modelcontextprotocol/server";
import { z } from "zod";
import { ApiClient, JsonObjectSchema, ToolResultSchema, run, segment, success } from "./core.js";

export const SERVER_NAME = "mcp-hubspot-crm";
export const SERVER_VERSION = "0.1.0";
type Env = Record<string, string | undefined>;
const Filter = z.object({ propertyName: z.string().min(1), operator: z.string().min(1), value: z.string().optional(), values: z.array(z.string()).optional(), highValue: z.string().optional() });

export function createServer(env: Env = {}): McpServer {
  const token = env.HUBSPOT_ACCESS_TOKEN?.trim();
  const api = new ApiClient({ baseUrl: env.HUBSPOT_API_BASE_URL || "https://api.hubapi.com", configured: Boolean(token), headers: token ? { Authorization: `Bearer ${token}` } : {} });
  const server = new McpServer({ name: SERVER_NAME, version: SERVER_VERSION });
  const ro = { readOnlyHint: true, idempotentHint: true };
  const searchInput = { query: z.string().optional(), filterGroups: z.array(z.object({ filters: z.array(Filter).min(1).max(6) })).max(5).optional(), sorts: z.array(z.string()).max(3).optional(), properties: z.array(z.string()).max(100).optional(), limit: z.number().int().min(1).max(200).default(50), after: z.string().optional() };

  server.registerTool("hubspot_status", { title: "HubSpot connection status", description: "Report non-secret CRM configuration.", inputSchema: z.object({}), outputSchema: ToolResultSchema, annotations: ro }, async () => success({ configured: api.configured, transport: "stdio-or-streamable-http" }));
  server.registerTool("search_contacts", { title: "Search contacts", description: "Search contacts with HubSpot filter groups and selected properties.", inputSchema: z.object(searchInput), outputSchema: ToolResultSchema, annotations: ro }, async (input) => run(() => api.request("POST", "/crm/v3/objects/contacts/search", { body: input })));
  server.registerTool("get_contact", { title: "Get contact", description: "Retrieve a contact and selected properties.", inputSchema: z.object({ contactId: z.string().min(1), properties: z.array(z.string()).optional(), associations: z.array(z.string()).optional() }), outputSchema: ToolResultSchema, annotations: ro }, async ({ contactId, properties, associations }) => run(() => api.request("GET", `/crm/v3/objects/contacts/${segment(contactId)}`, { query: { properties: properties?.join(","), associations: associations?.join(",") } })));
  server.registerTool("create_contact", { title: "Create contact", description: "Create a contact from CRM properties.", inputSchema: z.object({ properties: JsonObjectSchema, associations: z.array(JsonObjectSchema).optional() }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false } }, async ({ properties, associations }) => run(() => api.request("POST", "/crm/v3/objects/contacts", { body: { properties, associations } })));
  server.registerTool("update_contact", { title: "Update contact", description: "Patch contact properties by ID.", inputSchema: z.object({ contactId: z.string().min(1), properties: JsonObjectSchema }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true } }, async ({ contactId, properties }) => run(() => api.request("PATCH", `/crm/v3/objects/contacts/${segment(contactId)}`, { body: { properties } })));
  server.registerTool("search_deals", { title: "Search deals", description: "Search deals with filter groups and selected properties.", inputSchema: z.object(searchInput), outputSchema: ToolResultSchema, annotations: ro }, async (input) => run(() => api.request("POST", "/crm/v3/objects/deals/search", { body: input })));
  server.registerTool("get_deal", { title: "Get deal", description: "Retrieve one deal and selected associations.", inputSchema: z.object({ dealId: z.string().min(1), properties: z.array(z.string()).optional(), associations: z.array(z.string()).optional() }), outputSchema: ToolResultSchema, annotations: ro }, async ({ dealId, properties, associations }) => run(() => api.request("GET", `/crm/v3/objects/deals/${segment(dealId)}`, { query: { properties: properties?.join(","), associations: associations?.join(",") } })));
  server.registerTool("create_deal", { title: "Create deal", description: "Create a deal from CRM properties.", inputSchema: z.object({ properties: JsonObjectSchema, associations: z.array(JsonObjectSchema).optional() }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false } }, async ({ properties, associations }) => run(() => api.request("POST", "/crm/v3/objects/deals", { body: { properties, associations } })));
  server.registerTool("update_deal", { title: "Update deal", description: "Patch deal properties by ID.", inputSchema: z.object({ dealId: z.string().min(1), properties: JsonObjectSchema }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true } }, async ({ dealId, properties }) => run(() => api.request("PATCH", `/crm/v3/objects/deals/${segment(dealId)}`, { body: { properties } })));
  server.registerTool("associate_contact_deal", { title: "Associate contact and deal", description: "Create a labeled or unlabeled association between a contact and deal.", inputSchema: z.object({ contactId: z.string().min(1), dealId: z.string().min(1), associationTypeId: z.number().int().positive().default(4) }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true } }, async ({ contactId, dealId, associationTypeId }) => run(() => api.request("PUT", `/crm/v4/objects/contacts/${segment(contactId)}/associations/deals/${segment(dealId)}`, { body: [{ associationCategory: "HUBSPOT_DEFINED", associationTypeId }] })));
  server.registerTool("enroll_contact_in_workflow", { title: "Enroll contact in workflow", description: "Enroll a contact email in an existing HubSpot workflow using the supported workflow-enrollment endpoint.", inputSchema: z.object({ workflowId: z.string().min(1), contactEmail: z.string().email() }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false } }, async ({ workflowId, contactEmail }) => run(() => api.request("POST", `/automation/v2/workflows/${segment(workflowId)}/enrollments/contacts/${segment(contactEmail)}`)));
  server.registerTool("enroll_contact_in_sequence", { title: "Enroll contact in sequence", description: "Enroll a contact in a HubSpot sequence using the dated 2026-03 API.", inputSchema: z.object({ userId: z.string().min(1), contactId: z.string().min(1), sequenceId: z.string().min(1), senderEmail: z.string().email(), senderAliasAddress: z.string().email().optional() }), outputSchema: ToolResultSchema, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false } }, async ({ userId, contactId, sequenceId, senderEmail, senderAliasAddress }) => run(() => api.request("POST", "/automation/sequences/2026-03/enrollments", { query: { userId }, body: { contactId, sequenceId, senderEmail, senderAliasAddress } })));

  server.registerResource("hubspot-crm-status", "hubspot://server/status", { title: "HubSpot CRM server status", description: "Non-secret CRM and automation capabilities.", mimeType: "application/json" }, async (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify({ name: SERVER_NAME, version: SERVER_VERSION, configured: api.configured, tools: 12 }, null, 2) }] }));
  server.registerPrompt("hubspot_crm_workflow", { title: "Plan a HubSpot CRM workflow", description: "Prepare a search-first contact/deal workflow.", argsSchema: z.object({ objective: z.string().min(1), objectType: z.enum(["contact", "deal", "both"]).default("both") }) }, ({ objective, objectType }) => ({ messages: [{ role: "user", content: { type: "text", text: `Objective: ${objective}\nObjects: ${objectType}\nSearch and read existing records first. Confirm exact IDs and changed properties before writes. Treat workflow or sequence enrollment as an external communication effect requiring explicit confirmation.` } }] }));
  return server;
}
